//! GENERATED by `tools/bake_icons.py` -- do not hand-edit. Re-run:
//!   python tools/bake_icons.py
//!
//! Licence: MIT (microsoft/vscode-codicons,
//! <https://github.com/microsoft/vscode-codicons/blob/main/LICENSE>).
//! Source: raw.githubusercontent.com/microsoft/vscode-codicons/main/src/
//! icons/<slug>.svg, `fill="currentColor"` patched to `#cdd6f4`
//! (`pty_palette::GATE_FG`) before rasterizing -- see `../icons.rs`'s own
//! module doc for the full tier/pipeline explanation and
//! `tools/bake_icons.py`'s own header for the exact bake recipe. Per-icon
//! braille alpha thresholds below are chosen by `bake_icons.py`'s own
//! `choose_threshold` (an explicit override, replaying the original 7 rail
//! icons' hand-tuned constants unchanged, or an auto coverage-histogram
//! search) -- see that function, not prose duplicated per icon here, for
//! the selection reasoning; a `DEGRADED` line marks icons whose shape does
//! not survive at 8x12 even at the best achievable threshold.

use std::sync::LazyLock;

use uzor_tui::canvas::{CanvasMode, PixelCanvas};

use super::{build_sixel, rgba_to_canvas, BRAILLE_ICON_CELLS_TALL, BRAILLE_ICON_CELLS_WIDE};

/// Every baked icon this crate ships, sixel + braille + ascii tiers, one
/// enum covering the full catalog (not just the activity rail -- see
/// `../icons.rs`'s own module doc). Only the activity rail's original 7
/// variants are wired into a UI site today; the rest are baked and tested
/// but not yet drawn anywhere -- a deliberate, scoped-out next slice, not
/// an oversight.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum IconId {
    Files,
    SourceControl,
    Person,
    Project,
    SettingsGear,
    ChevronLeft,
    ChevronRight,
    ChevronDown,
    NewFile,
    NewFolder,
    Folder,
    FolderOpened,
    File,
    Save,
    Refresh,
    Add,
    Trash,
    Search,
    Check,
    Close,
    ArrowUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowSwap,
    GitCommit,
    GitBranch,
    Diff,
    DiffAdded,
    GitCompare,
    Repo,
    RepoForked,
    DebugStop,
    DebugRestart,
    Edit,
    History,
    Terminal,
    Output,
    CloudDownload,
    Ellipsis,
    Link,
    CircleFilled,
    CircleSlash,
    Warning,
    Error,
    Info,
    RunAll,
    Play,
    Sync,
    GoToFile,
    Pulse,
    Checklist,
    Eye,
    Layout,
    SplitHorizontal,
    SplitVertical,
    Preview,
}

impl IconId {
    pub const ALL: [IconId; 57] = [
        IconId::Files,
        IconId::SourceControl,
        IconId::Person,
        IconId::Project,
        IconId::SettingsGear,
        IconId::ChevronLeft,
        IconId::ChevronRight,
        IconId::ChevronDown,
        IconId::NewFile,
        IconId::NewFolder,
        IconId::Folder,
        IconId::FolderOpened,
        IconId::File,
        IconId::Save,
        IconId::Refresh,
        IconId::Add,
        IconId::Trash,
        IconId::Search,
        IconId::Check,
        IconId::Close,
        IconId::ArrowUp,
        IconId::ArrowDown,
        IconId::ArrowLeft,
        IconId::ArrowRight,
        IconId::ArrowSwap,
        IconId::GitCommit,
        IconId::GitBranch,
        IconId::Diff,
        IconId::DiffAdded,
        IconId::GitCompare,
        IconId::Repo,
        IconId::RepoForked,
        IconId::DebugStop,
        IconId::DebugRestart,
        IconId::Edit,
        IconId::History,
        IconId::Terminal,
        IconId::Output,
        IconId::CloudDownload,
        IconId::Ellipsis,
        IconId::Link,
        IconId::CircleFilled,
        IconId::CircleSlash,
        IconId::Warning,
        IconId::Error,
        IconId::Info,
        IconId::RunAll,
        IconId::Play,
        IconId::Sync,
        IconId::GoToFile,
        IconId::Pulse,
        IconId::Checklist,
        IconId::Eye,
        IconId::Layout,
        IconId::SplitHorizontal,
        IconId::SplitVertical,
        IconId::Preview,
    ];
}

/// Encoded sixel string for `id` -- see `../icons.rs::build_sixel`'s own
/// doc comment for why this is cached (`LazyLock`) rather than re-encoded
/// per call.
pub fn sixel(id: IconId) -> &'static str {
    match id {
        IconId::Files => FILES_SIXEL.as_str(),
        IconId::SourceControl => SOURCE_CONTROL_SIXEL.as_str(),
        IconId::Person => PERSON_SIXEL.as_str(),
        IconId::Project => PROJECT_SIXEL.as_str(),
        IconId::SettingsGear => SETTINGS_GEAR_SIXEL.as_str(),
        IconId::ChevronLeft => CHEVRON_LEFT_SIXEL.as_str(),
        IconId::ChevronRight => CHEVRON_RIGHT_SIXEL.as_str(),
        IconId::ChevronDown => CHEVRON_DOWN_SIXEL.as_str(),
        IconId::NewFile => NEW_FILE_SIXEL.as_str(),
        IconId::NewFolder => NEW_FOLDER_SIXEL.as_str(),
        IconId::Folder => FOLDER_SIXEL.as_str(),
        IconId::FolderOpened => FOLDER_OPENED_SIXEL.as_str(),
        IconId::File => FILE_SIXEL.as_str(),
        IconId::Save => SAVE_SIXEL.as_str(),
        IconId::Refresh => REFRESH_SIXEL.as_str(),
        IconId::Add => ADD_SIXEL.as_str(),
        IconId::Trash => TRASH_SIXEL.as_str(),
        IconId::Search => SEARCH_SIXEL.as_str(),
        IconId::Check => CHECK_SIXEL.as_str(),
        IconId::Close => CLOSE_SIXEL.as_str(),
        IconId::ArrowUp => ARROW_UP_SIXEL.as_str(),
        IconId::ArrowDown => ARROW_DOWN_SIXEL.as_str(),
        IconId::ArrowLeft => ARROW_LEFT_SIXEL.as_str(),
        IconId::ArrowRight => ARROW_RIGHT_SIXEL.as_str(),
        IconId::ArrowSwap => ARROW_SWAP_SIXEL.as_str(),
        IconId::GitCommit => GIT_COMMIT_SIXEL.as_str(),
        IconId::GitBranch => GIT_BRANCH_SIXEL.as_str(),
        IconId::Diff => DIFF_SIXEL.as_str(),
        IconId::DiffAdded => DIFF_ADDED_SIXEL.as_str(),
        IconId::GitCompare => GIT_COMPARE_SIXEL.as_str(),
        IconId::Repo => REPO_SIXEL.as_str(),
        IconId::RepoForked => REPO_FORKED_SIXEL.as_str(),
        IconId::DebugStop => DEBUG_STOP_SIXEL.as_str(),
        IconId::DebugRestart => DEBUG_RESTART_SIXEL.as_str(),
        IconId::Edit => EDIT_SIXEL.as_str(),
        IconId::History => HISTORY_SIXEL.as_str(),
        IconId::Terminal => TERMINAL_SIXEL.as_str(),
        IconId::Output => OUTPUT_SIXEL.as_str(),
        IconId::CloudDownload => CLOUD_DOWNLOAD_SIXEL.as_str(),
        IconId::Ellipsis => ELLIPSIS_SIXEL.as_str(),
        IconId::Link => LINK_SIXEL.as_str(),
        IconId::CircleFilled => CIRCLE_FILLED_SIXEL.as_str(),
        IconId::CircleSlash => CIRCLE_SLASH_SIXEL.as_str(),
        IconId::Warning => WARNING_SIXEL.as_str(),
        IconId::Error => ERROR_SIXEL.as_str(),
        IconId::Info => INFO_SIXEL.as_str(),
        IconId::RunAll => RUN_ALL_SIXEL.as_str(),
        IconId::Play => PLAY_SIXEL.as_str(),
        IconId::Sync => SYNC_SIXEL.as_str(),
        IconId::GoToFile => GO_TO_FILE_SIXEL.as_str(),
        IconId::Pulse => PULSE_SIXEL.as_str(),
        IconId::Checklist => CHECKLIST_SIXEL.as_str(),
        IconId::Eye => EYE_SIXEL.as_str(),
        IconId::Layout => LAYOUT_SIXEL.as_str(),
        IconId::SplitHorizontal => SPLIT_HORIZONTAL_SIXEL.as_str(),
        IconId::SplitVertical => SPLIT_VERTICAL_SIXEL.as_str(),
        IconId::Preview => PREVIEW_SIXEL.as_str(),
    }
}

/// Braille-tier [`PixelCanvas`] for `id` -- see `../icons.rs::rgba_to_canvas`'s
/// own doc comment for the alpha-threshold silhouette rule.
pub fn braille(id: IconId) -> &'static PixelCanvas {
    match id {
        IconId::Files => &*FILES_BRAILLE,
        IconId::SourceControl => &*SOURCE_CONTROL_BRAILLE,
        IconId::Person => &*PERSON_BRAILLE,
        IconId::Project => &*PROJECT_BRAILLE,
        IconId::SettingsGear => &*SETTINGS_GEAR_BRAILLE,
        IconId::ChevronLeft => &*CHEVRON_LEFT_BRAILLE,
        IconId::ChevronRight => &*CHEVRON_RIGHT_BRAILLE,
        IconId::ChevronDown => &*CHEVRON_DOWN_BRAILLE,
        IconId::NewFile => &*NEW_FILE_BRAILLE,
        IconId::NewFolder => &*NEW_FOLDER_BRAILLE,
        IconId::Folder => &*FOLDER_BRAILLE,
        IconId::FolderOpened => &*FOLDER_OPENED_BRAILLE,
        IconId::File => &*FILE_BRAILLE,
        IconId::Save => &*SAVE_BRAILLE,
        IconId::Refresh => &*REFRESH_BRAILLE,
        IconId::Add => &*ADD_BRAILLE,
        IconId::Trash => &*TRASH_BRAILLE,
        IconId::Search => &*SEARCH_BRAILLE,
        IconId::Check => &*CHECK_BRAILLE,
        IconId::Close => &*CLOSE_BRAILLE,
        IconId::ArrowUp => &*ARROW_UP_BRAILLE,
        IconId::ArrowDown => &*ARROW_DOWN_BRAILLE,
        IconId::ArrowLeft => &*ARROW_LEFT_BRAILLE,
        IconId::ArrowRight => &*ARROW_RIGHT_BRAILLE,
        IconId::ArrowSwap => &*ARROW_SWAP_BRAILLE,
        IconId::GitCommit => &*GIT_COMMIT_BRAILLE,
        IconId::GitBranch => &*GIT_BRANCH_BRAILLE,
        IconId::Diff => &*DIFF_BRAILLE,
        IconId::DiffAdded => &*DIFF_ADDED_BRAILLE,
        IconId::GitCompare => &*GIT_COMPARE_BRAILLE,
        IconId::Repo => &*REPO_BRAILLE,
        IconId::RepoForked => &*REPO_FORKED_BRAILLE,
        IconId::DebugStop => &*DEBUG_STOP_BRAILLE,
        IconId::DebugRestart => &*DEBUG_RESTART_BRAILLE,
        IconId::Edit => &*EDIT_BRAILLE,
        IconId::History => &*HISTORY_BRAILLE,
        IconId::Terminal => &*TERMINAL_BRAILLE,
        IconId::Output => &*OUTPUT_BRAILLE,
        IconId::CloudDownload => &*CLOUD_DOWNLOAD_BRAILLE,
        IconId::Ellipsis => &*ELLIPSIS_BRAILLE,
        IconId::Link => &*LINK_BRAILLE,
        IconId::CircleFilled => &*CIRCLE_FILLED_BRAILLE,
        IconId::CircleSlash => &*CIRCLE_SLASH_BRAILLE,
        IconId::Warning => &*WARNING_BRAILLE,
        IconId::Error => &*ERROR_BRAILLE,
        IconId::Info => &*INFO_BRAILLE,
        IconId::RunAll => &*RUN_ALL_BRAILLE,
        IconId::Play => &*PLAY_BRAILLE,
        IconId::Sync => &*SYNC_BRAILLE,
        IconId::GoToFile => &*GO_TO_FILE_BRAILLE,
        IconId::Pulse => &*PULSE_BRAILLE,
        IconId::Checklist => &*CHECKLIST_BRAILLE,
        IconId::Eye => &*EYE_BRAILLE,
        IconId::Layout => &*LAYOUT_BRAILLE,
        IconId::SplitHorizontal => &*SPLIT_HORIZONTAL_BRAILLE,
        IconId::SplitVertical => &*SPLIT_VERTICAL_BRAILLE,
        IconId::Preview => &*PREVIEW_BRAILLE,
    }
}

/// Short (<=2 char) plain-ASCII label for `id` -- the rail's own existing
/// letters (`F`/`G`/`A`/`K`/`S`/`<`/`>`) are reproduced unchanged for the
/// original 7; every other icon gets an obvious short mark (see
/// `tools/bake_icons.py::MANIFEST` for the reasoning per icon).
pub fn ascii(id: IconId) -> &'static str {
    match id {
        IconId::Files => "F",
        IconId::SourceControl => "G",
        IconId::Person => "A",
        IconId::Project => "K",
        IconId::SettingsGear => "S",
        IconId::ChevronLeft => "<",
        IconId::ChevronRight => ">",
        IconId::ChevronDown => "v",
        IconId::NewFile => "N+",
        IconId::NewFolder => "Nd",
        IconId::Folder => "Fd",
        IconId::FolderOpened => "Fo",
        IconId::File => "Fl",
        IconId::Save => "Sa",
        IconId::Refresh => "R",
        IconId::Add => "+",
        IconId::Trash => "Tr",
        IconId::Search => "Se",
        IconId::Check => "OK",
        IconId::Close => "x",
        IconId::ArrowUp => "^",
        IconId::ArrowDown => "v",
        IconId::ArrowLeft => "<",
        IconId::ArrowRight => ">",
        IconId::ArrowSwap => "<>",
        IconId::GitCommit => "Gc",
        IconId::GitBranch => "Gb",
        IconId::Diff => "Df",
        IconId::DiffAdded => "D+",
        IconId::GitCompare => "Gx",
        IconId::Repo => "Rp",
        IconId::RepoForked => "Rf",
        IconId::DebugStop => "Ds",
        IconId::DebugRestart => "Dr",
        IconId::Edit => "E",
        IconId::History => "H",
        IconId::Terminal => "T",
        IconId::Output => "O",
        IconId::CloudDownload => "Cd",
        IconId::Ellipsis => "..",
        IconId::Link => "Lk",
        IconId::CircleFilled => "Cf",
        IconId::CircleSlash => "Cs",
        IconId::Warning => "!",
        IconId::Error => "Er",
        IconId::Info => "i",
        IconId::RunAll => "R>",
        IconId::Play => "Pl",
        IconId::Sync => "Sy",
        IconId::GoToFile => "Gf",
        IconId::Pulse => "Pu",
        IconId::Checklist => "Cl",
        IconId::Eye => "Ey",
        IconId::Layout => "Ly",
        IconId::SplitHorizontal => "Sh",
        IconId::SplitVertical => "Sv",
        IconId::Preview => "Pv",
    }
}

// Raw baked-source lookups by id -- used only by this crate's own unit
// tests (byte-length assertions, and the rail's own no-visual-regression
// check against `../icons.rs`'s hand-written test module).
#[cfg(test)]
pub(crate) fn sixel_source_rgba(id: IconId) -> &'static [u8] {
    match id {
        IconId::Files => FILES_RGBA,
        IconId::SourceControl => SOURCE_CONTROL_RGBA,
        IconId::Person => PERSON_RGBA,
        IconId::Project => PROJECT_RGBA,
        IconId::SettingsGear => SETTINGS_GEAR_RGBA,
        IconId::ChevronLeft => CHEVRON_LEFT_RGBA,
        IconId::ChevronRight => CHEVRON_RIGHT_RGBA,
        IconId::ChevronDown => CHEVRON_DOWN_RGBA,
        IconId::NewFile => NEW_FILE_RGBA,
        IconId::NewFolder => NEW_FOLDER_RGBA,
        IconId::Folder => FOLDER_RGBA,
        IconId::FolderOpened => FOLDER_OPENED_RGBA,
        IconId::File => FILE_RGBA,
        IconId::Save => SAVE_RGBA,
        IconId::Refresh => REFRESH_RGBA,
        IconId::Add => ADD_RGBA,
        IconId::Trash => TRASH_RGBA,
        IconId::Search => SEARCH_RGBA,
        IconId::Check => CHECK_RGBA,
        IconId::Close => CLOSE_RGBA,
        IconId::ArrowUp => ARROW_UP_RGBA,
        IconId::ArrowDown => ARROW_DOWN_RGBA,
        IconId::ArrowLeft => ARROW_LEFT_RGBA,
        IconId::ArrowRight => ARROW_RIGHT_RGBA,
        IconId::ArrowSwap => ARROW_SWAP_RGBA,
        IconId::GitCommit => GIT_COMMIT_RGBA,
        IconId::GitBranch => GIT_BRANCH_RGBA,
        IconId::Diff => DIFF_RGBA,
        IconId::DiffAdded => DIFF_ADDED_RGBA,
        IconId::GitCompare => GIT_COMPARE_RGBA,
        IconId::Repo => REPO_RGBA,
        IconId::RepoForked => REPO_FORKED_RGBA,
        IconId::DebugStop => DEBUG_STOP_RGBA,
        IconId::DebugRestart => DEBUG_RESTART_RGBA,
        IconId::Edit => EDIT_RGBA,
        IconId::History => HISTORY_RGBA,
        IconId::Terminal => TERMINAL_RGBA,
        IconId::Output => OUTPUT_RGBA,
        IconId::CloudDownload => CLOUD_DOWNLOAD_RGBA,
        IconId::Ellipsis => ELLIPSIS_RGBA,
        IconId::Link => LINK_RGBA,
        IconId::CircleFilled => CIRCLE_FILLED_RGBA,
        IconId::CircleSlash => CIRCLE_SLASH_RGBA,
        IconId::Warning => WARNING_RGBA,
        IconId::Error => ERROR_RGBA,
        IconId::Info => INFO_RGBA,
        IconId::RunAll => RUN_ALL_RGBA,
        IconId::Play => PLAY_RGBA,
        IconId::Sync => SYNC_RGBA,
        IconId::GoToFile => GO_TO_FILE_RGBA,
        IconId::Pulse => PULSE_RGBA,
        IconId::Checklist => CHECKLIST_RGBA,
        IconId::Eye => EYE_RGBA,
        IconId::Layout => LAYOUT_RGBA,
        IconId::SplitHorizontal => SPLIT_HORIZONTAL_RGBA,
        IconId::SplitVertical => SPLIT_VERTICAL_RGBA,
        IconId::Preview => PREVIEW_RGBA,
    }
}

#[cfg(test)]
pub(crate) fn braille_source_rgba(id: IconId) -> &'static [u8] {
    match id {
        IconId::Files => FILES_BRAILLE_RGBA,
        IconId::SourceControl => SOURCE_CONTROL_BRAILLE_RGBA,
        IconId::Person => PERSON_BRAILLE_RGBA,
        IconId::Project => PROJECT_BRAILLE_RGBA,
        IconId::SettingsGear => SETTINGS_GEAR_BRAILLE_RGBA,
        IconId::ChevronLeft => CHEVRON_LEFT_BRAILLE_RGBA,
        IconId::ChevronRight => CHEVRON_RIGHT_BRAILLE_RGBA,
        IconId::ChevronDown => CHEVRON_DOWN_BRAILLE_RGBA,
        IconId::NewFile => NEW_FILE_BRAILLE_RGBA,
        IconId::NewFolder => NEW_FOLDER_BRAILLE_RGBA,
        IconId::Folder => FOLDER_BRAILLE_RGBA,
        IconId::FolderOpened => FOLDER_OPENED_BRAILLE_RGBA,
        IconId::File => FILE_BRAILLE_RGBA,
        IconId::Save => SAVE_BRAILLE_RGBA,
        IconId::Refresh => REFRESH_BRAILLE_RGBA,
        IconId::Add => ADD_BRAILLE_RGBA,
        IconId::Trash => TRASH_BRAILLE_RGBA,
        IconId::Search => SEARCH_BRAILLE_RGBA,
        IconId::Check => CHECK_BRAILLE_RGBA,
        IconId::Close => CLOSE_BRAILLE_RGBA,
        IconId::ArrowUp => ARROW_UP_BRAILLE_RGBA,
        IconId::ArrowDown => ARROW_DOWN_BRAILLE_RGBA,
        IconId::ArrowLeft => ARROW_LEFT_BRAILLE_RGBA,
        IconId::ArrowRight => ARROW_RIGHT_BRAILLE_RGBA,
        IconId::ArrowSwap => ARROW_SWAP_BRAILLE_RGBA,
        IconId::GitCommit => GIT_COMMIT_BRAILLE_RGBA,
        IconId::GitBranch => GIT_BRANCH_BRAILLE_RGBA,
        IconId::Diff => DIFF_BRAILLE_RGBA,
        IconId::DiffAdded => DIFF_ADDED_BRAILLE_RGBA,
        IconId::GitCompare => GIT_COMPARE_BRAILLE_RGBA,
        IconId::Repo => REPO_BRAILLE_RGBA,
        IconId::RepoForked => REPO_FORKED_BRAILLE_RGBA,
        IconId::DebugStop => DEBUG_STOP_BRAILLE_RGBA,
        IconId::DebugRestart => DEBUG_RESTART_BRAILLE_RGBA,
        IconId::Edit => EDIT_BRAILLE_RGBA,
        IconId::History => HISTORY_BRAILLE_RGBA,
        IconId::Terminal => TERMINAL_BRAILLE_RGBA,
        IconId::Output => OUTPUT_BRAILLE_RGBA,
        IconId::CloudDownload => CLOUD_DOWNLOAD_BRAILLE_RGBA,
        IconId::Ellipsis => ELLIPSIS_BRAILLE_RGBA,
        IconId::Link => LINK_BRAILLE_RGBA,
        IconId::CircleFilled => CIRCLE_FILLED_BRAILLE_RGBA,
        IconId::CircleSlash => CIRCLE_SLASH_BRAILLE_RGBA,
        IconId::Warning => WARNING_BRAILLE_RGBA,
        IconId::Error => ERROR_BRAILLE_RGBA,
        IconId::Info => INFO_BRAILLE_RGBA,
        IconId::RunAll => RUN_ALL_BRAILLE_RGBA,
        IconId::Play => PLAY_BRAILLE_RGBA,
        IconId::Sync => SYNC_BRAILLE_RGBA,
        IconId::GoToFile => GO_TO_FILE_BRAILLE_RGBA,
        IconId::Pulse => PULSE_BRAILLE_RGBA,
        IconId::Checklist => CHECKLIST_BRAILLE_RGBA,
        IconId::Eye => EYE_BRAILLE_RGBA,
        IconId::Layout => LAYOUT_BRAILLE_RGBA,
        IconId::SplitHorizontal => SPLIT_HORIZONTAL_BRAILLE_RGBA,
        IconId::SplitVertical => SPLIT_VERTICAL_BRAILLE_RGBA,
        IconId::Preview => PREVIEW_BRAILLE_RGBA,
    }
}

// ---- Files (files) --------------------------------------------------

const FILES_RGBA: &[u8] = include_bytes!("files.rgba");
static FILES_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(FILES_RGBA));

const FILES_BRAILLE_RGBA: &[u8] = include_bytes!("files_braille.rgba");
/// ~40% coverage (102/255), override (replaying the pre-existing rail icon's own hand-tuned constant, unchanged) -- 31/96 dots lit at this threshold.
const FILES_BRAILLE_ALPHA_THRESHOLD: u8 = 102;
static FILES_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        FILES_BRAILLE_RGBA,
        FILES_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- SourceControl (source-control) ---------------------------------

const SOURCE_CONTROL_RGBA: &[u8] = include_bytes!("source_control.rgba");
static SOURCE_CONTROL_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(SOURCE_CONTROL_RGBA));

const SOURCE_CONTROL_BRAILLE_RGBA: &[u8] = include_bytes!("source_control_braille.rgba");
/// ~40% coverage (102/255), override (replaying the pre-existing rail icon's own hand-tuned constant, unchanged) -- 20/96 dots lit at this threshold.
const SOURCE_CONTROL_BRAILLE_ALPHA_THRESHOLD: u8 = 102;
static SOURCE_CONTROL_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        SOURCE_CONTROL_BRAILLE_RGBA,
        SOURCE_CONTROL_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Person (person) ------------------------------------------------

const PERSON_RGBA: &[u8] = include_bytes!("person.rgba");
static PERSON_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(PERSON_RGBA));

const PERSON_BRAILLE_RGBA: &[u8] = include_bytes!("person_braille.rgba");
/// ~35% coverage (89/255), override (replaying the pre-existing rail icon's own hand-tuned constant, unchanged) -- 17/96 dots lit at this threshold.
const PERSON_BRAILLE_ALPHA_THRESHOLD: u8 = 89;
static PERSON_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        PERSON_BRAILLE_RGBA,
        PERSON_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Project (project) ----------------------------------------------

const PROJECT_RGBA: &[u8] = include_bytes!("project.rgba");
static PROJECT_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(PROJECT_RGBA));

const PROJECT_BRAILLE_RGBA: &[u8] = include_bytes!("project_braille.rgba");
/// ~40% coverage (102/255), override (replaying the pre-existing rail icon's own hand-tuned constant, unchanged) -- 22/96 dots lit at this threshold.
const PROJECT_BRAILLE_ALPHA_THRESHOLD: u8 = 102;
static PROJECT_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        PROJECT_BRAILLE_RGBA,
        PROJECT_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- SettingsGear (settings-gear) -----------------------------------

const SETTINGS_GEAR_RGBA: &[u8] = include_bytes!("settings_gear.rgba");
static SETTINGS_GEAR_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(SETTINGS_GEAR_RGBA));

const SETTINGS_GEAR_BRAILLE_RGBA: &[u8] = include_bytes!("settings_gear_braille.rgba");
/// ~35% coverage (89/255), override (replaying the pre-existing rail icon's own hand-tuned constant, unchanged) -- 24/96 dots lit at this threshold.
/// DEGRADED: teeth merge into a round, hollow-centered blob -- an honest 8x12 resolution ceiling, not a threshold bug (pre-existing, documented in src/icons.rs).
const SETTINGS_GEAR_BRAILLE_ALPHA_THRESHOLD: u8 = 89;
static SETTINGS_GEAR_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        SETTINGS_GEAR_BRAILLE_RGBA,
        SETTINGS_GEAR_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- ChevronLeft (chevron-left) -------------------------------------

const CHEVRON_LEFT_RGBA: &[u8] = include_bytes!("chevron_left.rgba");
static CHEVRON_LEFT_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(CHEVRON_LEFT_RGBA));

const CHEVRON_LEFT_BRAILLE_RGBA: &[u8] = include_bytes!("chevron_left_braille.rgba");
/// ~30% coverage (77/255), override (replaying the pre-existing rail icon's own hand-tuned constant, unchanged) -- 12/96 dots lit at this threshold.
const CHEVRON_LEFT_BRAILLE_ALPHA_THRESHOLD: u8 = 77;
static CHEVRON_LEFT_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        CHEVRON_LEFT_BRAILLE_RGBA,
        CHEVRON_LEFT_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- ChevronRight (chevron-right) -----------------------------------

const CHEVRON_RIGHT_RGBA: &[u8] = include_bytes!("chevron_right.rgba");
static CHEVRON_RIGHT_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(CHEVRON_RIGHT_RGBA));

const CHEVRON_RIGHT_BRAILLE_RGBA: &[u8] = include_bytes!("chevron_right_braille.rgba");
/// ~30% coverage (77/255), override (replaying the pre-existing rail icon's own hand-tuned constant, unchanged) -- 12/96 dots lit at this threshold.
const CHEVRON_RIGHT_BRAILLE_ALPHA_THRESHOLD: u8 = 77;
static CHEVRON_RIGHT_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        CHEVRON_RIGHT_BRAILLE_RGBA,
        CHEVRON_RIGHT_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- ChevronDown (chevron-down) -------------------------------------

const CHEVRON_DOWN_RGBA: &[u8] = include_bytes!("chevron_down.rgba");
static CHEVRON_DOWN_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(CHEVRON_DOWN_RGBA));

const CHEVRON_DOWN_BRAILLE_RGBA: &[u8] = include_bytes!("chevron_down_braille.rgba");
/// ~6% coverage (15/255), auto-selected by bake_icons.py::choose_threshold -- 14/96 dots lit at this threshold.
const CHEVRON_DOWN_BRAILLE_ALPHA_THRESHOLD: u8 = 15;
static CHEVRON_DOWN_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        CHEVRON_DOWN_BRAILLE_RGBA,
        CHEVRON_DOWN_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- NewFile (new-file) ---------------------------------------------

const NEW_FILE_RGBA: &[u8] = include_bytes!("new_file.rgba");
static NEW_FILE_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(NEW_FILE_RGBA));

const NEW_FILE_BRAILLE_RGBA: &[u8] = include_bytes!("new_file_braille.rgba");
/// ~50% coverage (128/255), auto-selected by bake_icons.py::choose_threshold -- 23/96 dots lit at this threshold.
const NEW_FILE_BRAILLE_ALPHA_THRESHOLD: u8 = 128;
static NEW_FILE_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        NEW_FILE_BRAILLE_RGBA,
        NEW_FILE_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- NewFolder (new-folder) -----------------------------------------

const NEW_FOLDER_RGBA: &[u8] = include_bytes!("new_folder.rgba");
static NEW_FOLDER_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(NEW_FOLDER_RGBA));

const NEW_FOLDER_BRAILLE_RGBA: &[u8] = include_bytes!("new_folder_braille.rgba");
/// ~50% coverage (128/255), auto-selected by bake_icons.py::choose_threshold -- 27/96 dots lit at this threshold.
const NEW_FOLDER_BRAILLE_ALPHA_THRESHOLD: u8 = 128;
static NEW_FOLDER_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        NEW_FOLDER_BRAILLE_RGBA,
        NEW_FOLDER_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Folder (folder) ------------------------------------------------

const FOLDER_RGBA: &[u8] = include_bytes!("folder.rgba");
static FOLDER_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(FOLDER_RGBA));

const FOLDER_BRAILLE_RGBA: &[u8] = include_bytes!("folder_braille.rgba");
/// ~50% coverage (128/255), auto-selected by bake_icons.py::choose_threshold -- 20/96 dots lit at this threshold.
const FOLDER_BRAILLE_ALPHA_THRESHOLD: u8 = 128;
static FOLDER_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        FOLDER_BRAILLE_RGBA,
        FOLDER_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- FolderOpened (folder-opened) -----------------------------------

const FOLDER_OPENED_RGBA: &[u8] = include_bytes!("folder_opened.rgba");
static FOLDER_OPENED_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(FOLDER_OPENED_RGBA));

const FOLDER_OPENED_BRAILLE_RGBA: &[u8] = include_bytes!("folder_opened_braille.rgba");
/// ~50% coverage (128/255), auto-selected by bake_icons.py::choose_threshold -- 20/96 dots lit at this threshold.
const FOLDER_OPENED_BRAILLE_ALPHA_THRESHOLD: u8 = 128;
static FOLDER_OPENED_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        FOLDER_OPENED_BRAILLE_RGBA,
        FOLDER_OPENED_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- File (file) ----------------------------------------------------

const FILE_RGBA: &[u8] = include_bytes!("file.rgba");
static FILE_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(FILE_RGBA));

const FILE_BRAILLE_RGBA: &[u8] = include_bytes!("file_braille.rgba");
/// ~45% coverage (115/255), auto-selected by bake_icons.py::choose_threshold -- 20/96 dots lit at this threshold.
const FILE_BRAILLE_ALPHA_THRESHOLD: u8 = 115;
static FILE_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        FILE_BRAILLE_RGBA,
        FILE_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Save (save) ----------------------------------------------------

const SAVE_RGBA: &[u8] = include_bytes!("save.rgba");
static SAVE_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(SAVE_RGBA));

const SAVE_BRAILLE_RGBA: &[u8] = include_bytes!("save_braille.rgba");
/// ~50% coverage (128/255), auto-selected by bake_icons.py::choose_threshold -- 24/96 dots lit at this threshold.
const SAVE_BRAILLE_ALPHA_THRESHOLD: u8 = 128;
static SAVE_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        SAVE_BRAILLE_RGBA,
        SAVE_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Refresh (refresh) ----------------------------------------------

const REFRESH_RGBA: &[u8] = include_bytes!("refresh.rgba");
static REFRESH_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(REFRESH_RGBA));

const REFRESH_BRAILLE_RGBA: &[u8] = include_bytes!("refresh_braille.rgba");
/// ~10% coverage (26/255), auto-selected by bake_icons.py::choose_threshold -- 21/96 dots lit at this threshold.
const REFRESH_BRAILLE_ALPHA_THRESHOLD: u8 = 26;
static REFRESH_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        REFRESH_BRAILLE_RGBA,
        REFRESH_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Add (add) ------------------------------------------------------

const ADD_RGBA: &[u8] = include_bytes!("add.rgba");
static ADD_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(ADD_RGBA));

const ADD_BRAILLE_RGBA: &[u8] = include_bytes!("add_braille.rgba");
/// ~6% coverage (15/255), auto-selected by bake_icons.py::choose_threshold -- 13/96 dots lit at this threshold.
const ADD_BRAILLE_ALPHA_THRESHOLD: u8 = 15;
static ADD_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        ADD_BRAILLE_RGBA,
        ADD_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Trash (trash) --------------------------------------------------

const TRASH_RGBA: &[u8] = include_bytes!("trash.rgba");
static TRASH_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(TRASH_RGBA));

const TRASH_BRAILLE_RGBA: &[u8] = include_bytes!("trash_braille.rgba");
/// ~50% coverage (128/255), auto-selected by bake_icons.py::choose_threshold -- 18/96 dots lit at this threshold.
const TRASH_BRAILLE_ALPHA_THRESHOLD: u8 = 128;
static TRASH_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        TRASH_BRAILLE_RGBA,
        TRASH_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Search (search) ------------------------------------------------

const SEARCH_RGBA: &[u8] = include_bytes!("search.rgba");
static SEARCH_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(SEARCH_RGBA));

const SEARCH_BRAILLE_RGBA: &[u8] = include_bytes!("search_braille.rgba");
/// ~15% coverage (38/255), auto-selected by bake_icons.py::choose_threshold -- 21/96 dots lit at this threshold.
const SEARCH_BRAILLE_ALPHA_THRESHOLD: u8 = 38;
static SEARCH_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        SEARCH_BRAILLE_RGBA,
        SEARCH_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Check (check) --------------------------------------------------

const CHECK_RGBA: &[u8] = include_bytes!("check.rgba");
static CHECK_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(CHECK_RGBA));

const CHECK_BRAILLE_RGBA: &[u8] = include_bytes!("check_braille.rgba");
/// ~6% coverage (15/255), auto-selected by bake_icons.py::choose_threshold -- 13/96 dots lit at this threshold.
const CHECK_BRAILLE_ALPHA_THRESHOLD: u8 = 15;
static CHECK_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        CHECK_BRAILLE_RGBA,
        CHECK_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Close (close) --------------------------------------------------

const CLOSE_RGBA: &[u8] = include_bytes!("close.rgba");
static CLOSE_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(CLOSE_RGBA));

const CLOSE_BRAILLE_RGBA: &[u8] = include_bytes!("close_braille.rgba");
/// ~30% coverage (77/255), override, hand-picked after reviewing bake_icons.py's own auto-suggested preview -- 12/96 dots lit at this threshold.
const CLOSE_BRAILLE_ALPHA_THRESHOLD: u8 = 77;
static CLOSE_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        CLOSE_BRAILLE_RGBA,
        CLOSE_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- ArrowUp (arrow-up) ---------------------------------------------

const ARROW_UP_RGBA: &[u8] = include_bytes!("arrow_up.rgba");
static ARROW_UP_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(ARROW_UP_RGBA));

const ARROW_UP_BRAILLE_RGBA: &[u8] = include_bytes!("arrow_up_braille.rgba");
/// ~6% coverage (15/255), auto-selected by bake_icons.py::choose_threshold -- 16/96 dots lit at this threshold.
const ARROW_UP_BRAILLE_ALPHA_THRESHOLD: u8 = 15;
static ARROW_UP_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        ARROW_UP_BRAILLE_RGBA,
        ARROW_UP_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- ArrowDown (arrow-down) -----------------------------------------

const ARROW_DOWN_RGBA: &[u8] = include_bytes!("arrow_down.rgba");
static ARROW_DOWN_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(ARROW_DOWN_RGBA));

const ARROW_DOWN_BRAILLE_RGBA: &[u8] = include_bytes!("arrow_down_braille.rgba");
/// ~6% coverage (15/255), auto-selected by bake_icons.py::choose_threshold -- 16/96 dots lit at this threshold.
const ARROW_DOWN_BRAILLE_ALPHA_THRESHOLD: u8 = 15;
static ARROW_DOWN_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        ARROW_DOWN_BRAILLE_RGBA,
        ARROW_DOWN_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- ArrowLeft (arrow-left) -----------------------------------------

const ARROW_LEFT_RGBA: &[u8] = include_bytes!("arrow_left.rgba");
static ARROW_LEFT_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(ARROW_LEFT_RGBA));

const ARROW_LEFT_BRAILLE_RGBA: &[u8] = include_bytes!("arrow_left_braille.rgba");
/// ~6% coverage (15/255), auto-selected by bake_icons.py::choose_threshold -- 16/96 dots lit at this threshold.
const ARROW_LEFT_BRAILLE_ALPHA_THRESHOLD: u8 = 15;
static ARROW_LEFT_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        ARROW_LEFT_BRAILLE_RGBA,
        ARROW_LEFT_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- ArrowRight (arrow-right) ---------------------------------------

const ARROW_RIGHT_RGBA: &[u8] = include_bytes!("arrow_right.rgba");
static ARROW_RIGHT_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(ARROW_RIGHT_RGBA));

const ARROW_RIGHT_BRAILLE_RGBA: &[u8] = include_bytes!("arrow_right_braille.rgba");
/// ~6% coverage (15/255), auto-selected by bake_icons.py::choose_threshold -- 16/96 dots lit at this threshold.
const ARROW_RIGHT_BRAILLE_ALPHA_THRESHOLD: u8 = 15;
static ARROW_RIGHT_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        ARROW_RIGHT_BRAILLE_RGBA,
        ARROW_RIGHT_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- ArrowSwap (arrow-swap) -----------------------------------------

const ARROW_SWAP_RGBA: &[u8] = include_bytes!("arrow_swap.rgba");
static ARROW_SWAP_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(ARROW_SWAP_RGBA));

const ARROW_SWAP_BRAILLE_RGBA: &[u8] = include_bytes!("arrow_swap_braille.rgba");
/// ~30% coverage (77/255), auto-selected by bake_icons.py::choose_threshold -- 18/96 dots lit at this threshold.
const ARROW_SWAP_BRAILLE_ALPHA_THRESHOLD: u8 = 77;
static ARROW_SWAP_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        ARROW_SWAP_BRAILLE_RGBA,
        ARROW_SWAP_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- GitCommit (git-commit) -----------------------------------------

const GIT_COMMIT_RGBA: &[u8] = include_bytes!("git_commit.rgba");
static GIT_COMMIT_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(GIT_COMMIT_RGBA));

const GIT_COMMIT_BRAILLE_RGBA: &[u8] = include_bytes!("git_commit_braille.rgba");
/// ~10% coverage (26/255), auto-selected by bake_icons.py::choose_threshold -- 20/96 dots lit at this threshold.
const GIT_COMMIT_BRAILLE_ALPHA_THRESHOLD: u8 = 26;
static GIT_COMMIT_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        GIT_COMMIT_BRAILLE_RGBA,
        GIT_COMMIT_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- GitBranch (git-branch) -----------------------------------------

const GIT_BRANCH_RGBA: &[u8] = include_bytes!("git_branch.rgba");
static GIT_BRANCH_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(GIT_BRANCH_RGBA));

const GIT_BRANCH_BRAILLE_RGBA: &[u8] = include_bytes!("git_branch_braille.rgba");
/// ~40% coverage (102/255), auto-selected by bake_icons.py::choose_threshold -- 20/96 dots lit at this threshold.
const GIT_BRANCH_BRAILLE_ALPHA_THRESHOLD: u8 = 102;
static GIT_BRANCH_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        GIT_BRANCH_BRAILLE_RGBA,
        GIT_BRANCH_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Diff (diff) ----------------------------------------------------

const DIFF_RGBA: &[u8] = include_bytes!("diff.rgba");
static DIFF_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(DIFF_RGBA));

const DIFF_BRAILLE_RGBA: &[u8] = include_bytes!("diff_braille.rgba");
/// ~50% coverage (128/255), auto-selected by bake_icons.py::choose_threshold -- 28/96 dots lit at this threshold.
const DIFF_BRAILLE_ALPHA_THRESHOLD: u8 = 128;
static DIFF_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        DIFF_BRAILLE_RGBA,
        DIFF_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- DiffAdded (diff-added) -----------------------------------------

const DIFF_ADDED_RGBA: &[u8] = include_bytes!("diff_added.rgba");
static DIFF_ADDED_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(DIFF_ADDED_RGBA));

const DIFF_ADDED_BRAILLE_RGBA: &[u8] = include_bytes!("diff_added_braille.rgba");
/// ~50% coverage (128/255), auto-selected by bake_icons.py::choose_threshold -- 22/96 dots lit at this threshold.
const DIFF_ADDED_BRAILLE_ALPHA_THRESHOLD: u8 = 128;
static DIFF_ADDED_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        DIFF_ADDED_BRAILLE_RGBA,
        DIFF_ADDED_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- GitCompare (git-compare) ---------------------------------------

const GIT_COMPARE_RGBA: &[u8] = include_bytes!("git_compare.rgba");
static GIT_COMPARE_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(GIT_COMPARE_RGBA));

const GIT_COMPARE_BRAILLE_RGBA: &[u8] = include_bytes!("git_compare_braille.rgba");
/// ~40% coverage (102/255), auto-selected by bake_icons.py::choose_threshold -- 22/96 dots lit at this threshold.
const GIT_COMPARE_BRAILLE_ALPHA_THRESHOLD: u8 = 102;
static GIT_COMPARE_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        GIT_COMPARE_BRAILLE_RGBA,
        GIT_COMPARE_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Repo (repo) ----------------------------------------------------

const REPO_RGBA: &[u8] = include_bytes!("repo.rgba");
static REPO_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(REPO_RGBA));

const REPO_BRAILLE_RGBA: &[u8] = include_bytes!("repo_braille.rgba");
/// ~45% coverage (115/255), auto-selected by bake_icons.py::choose_threshold -- 24/96 dots lit at this threshold.
const REPO_BRAILLE_ALPHA_THRESHOLD: u8 = 115;
static REPO_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        REPO_BRAILLE_RGBA,
        REPO_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- RepoForked (repo-forked) ---------------------------------------

const REPO_FORKED_RGBA: &[u8] = include_bytes!("repo_forked.rgba");
static REPO_FORKED_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(REPO_FORKED_RGBA));

const REPO_FORKED_BRAILLE_RGBA: &[u8] = include_bytes!("repo_forked_braille.rgba");
/// ~35% coverage (89/255), auto-selected by bake_icons.py::choose_threshold -- 19/96 dots lit at this threshold.
const REPO_FORKED_BRAILLE_ALPHA_THRESHOLD: u8 = 89;
static REPO_FORKED_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        REPO_FORKED_BRAILLE_RGBA,
        REPO_FORKED_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- DebugStop (debug-stop) -----------------------------------------

const DEBUG_STOP_RGBA: &[u8] = include_bytes!("debug_stop.rgba");
static DEBUG_STOP_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(DEBUG_STOP_RGBA));

const DEBUG_STOP_BRAILLE_RGBA: &[u8] = include_bytes!("debug_stop_braille.rgba");
/// ~58% coverage (148/255), auto-selected by bake_icons.py::choose_threshold -- 20/96 dots lit at this threshold.
const DEBUG_STOP_BRAILLE_ALPHA_THRESHOLD: u8 = 148;
static DEBUG_STOP_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        DEBUG_STOP_BRAILLE_RGBA,
        DEBUG_STOP_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- DebugRestart (debug-restart) -----------------------------------

const DEBUG_RESTART_RGBA: &[u8] = include_bytes!("debug_restart.rgba");
static DEBUG_RESTART_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(DEBUG_RESTART_RGBA));

const DEBUG_RESTART_BRAILLE_RGBA: &[u8] = include_bytes!("debug_restart_braille.rgba");
/// ~45% coverage (115/255), auto-selected by bake_icons.py::choose_threshold -- 18/96 dots lit at this threshold.
const DEBUG_RESTART_BRAILLE_ALPHA_THRESHOLD: u8 = 115;
static DEBUG_RESTART_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        DEBUG_RESTART_BRAILLE_RGBA,
        DEBUG_RESTART_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Edit (edit) ----------------------------------------------------

const EDIT_RGBA: &[u8] = include_bytes!("edit.rgba");
static EDIT_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(EDIT_RGBA));

const EDIT_BRAILLE_RGBA: &[u8] = include_bytes!("edit_braille.rgba");
/// ~30% coverage (77/255), auto-selected by bake_icons.py::choose_threshold -- 24/96 dots lit at this threshold.
const EDIT_BRAILLE_ALPHA_THRESHOLD: u8 = 77;
static EDIT_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        EDIT_BRAILLE_RGBA,
        EDIT_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- History (history) ----------------------------------------------

const HISTORY_RGBA: &[u8] = include_bytes!("history.rgba");
static HISTORY_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(HISTORY_RGBA));

const HISTORY_BRAILLE_RGBA: &[u8] = include_bytes!("history_braille.rgba");
/// ~45% coverage (115/255), auto-selected by bake_icons.py::choose_threshold -- 19/96 dots lit at this threshold.
const HISTORY_BRAILLE_ALPHA_THRESHOLD: u8 = 115;
static HISTORY_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        HISTORY_BRAILLE_RGBA,
        HISTORY_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Terminal (terminal) --------------------------------------------

const TERMINAL_RGBA: &[u8] = include_bytes!("terminal.rgba");
static TERMINAL_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(TERMINAL_RGBA));

const TERMINAL_BRAILLE_RGBA: &[u8] = include_bytes!("terminal_braille.rgba");
/// ~50% coverage (128/255), auto-selected by bake_icons.py::choose_threshold -- 19/96 dots lit at this threshold.
const TERMINAL_BRAILLE_ALPHA_THRESHOLD: u8 = 128;
static TERMINAL_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        TERMINAL_BRAILLE_RGBA,
        TERMINAL_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Output (output) ------------------------------------------------

const OUTPUT_RGBA: &[u8] = include_bytes!("output.rgba");
static OUTPUT_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(OUTPUT_RGBA));

const OUTPUT_BRAILLE_RGBA: &[u8] = include_bytes!("output_braille.rgba");
/// ~45% coverage (115/255), auto-selected by bake_icons.py::choose_threshold -- 18/96 dots lit at this threshold.
const OUTPUT_BRAILLE_ALPHA_THRESHOLD: u8 = 115;
static OUTPUT_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        OUTPUT_BRAILLE_RGBA,
        OUTPUT_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- CloudDownload (cloud-download) ---------------------------------

const CLOUD_DOWNLOAD_RGBA: &[u8] = include_bytes!("cloud_download.rgba");
static CLOUD_DOWNLOAD_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(CLOUD_DOWNLOAD_RGBA));

const CLOUD_DOWNLOAD_BRAILLE_RGBA: &[u8] = include_bytes!("cloud_download_braille.rgba");
/// ~45% coverage (115/255), auto-selected by bake_icons.py::choose_threshold -- 19/96 dots lit at this threshold.
const CLOUD_DOWNLOAD_BRAILLE_ALPHA_THRESHOLD: u8 = 115;
static CLOUD_DOWNLOAD_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        CLOUD_DOWNLOAD_BRAILLE_RGBA,
        CLOUD_DOWNLOAD_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Ellipsis (ellipsis) --------------------------------------------

const ELLIPSIS_RGBA: &[u8] = include_bytes!("ellipsis.rgba");
static ELLIPSIS_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(ELLIPSIS_RGBA));

const ELLIPSIS_BRAILLE_RGBA: &[u8] = include_bytes!("ellipsis_braille.rgba");
/// ~15% coverage (38/255), override, hand-picked after reviewing bake_icons.py's own auto-suggested preview -- 12/96 dots lit at this threshold.
/// DEGRADED: the 3 dots merge into ONE solid horizontal band (verified: every alpha value in the baked buffer is 0, 48, or 49 -- no threshold separates them); reads as a short dash/bar, not 3 distinct dots.
const ELLIPSIS_BRAILLE_ALPHA_THRESHOLD: u8 = 38;
static ELLIPSIS_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        ELLIPSIS_BRAILLE_RGBA,
        ELLIPSIS_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Link (link) ----------------------------------------------------

const LINK_RGBA: &[u8] = include_bytes!("link.rgba");
static LINK_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(LINK_RGBA));

const LINK_BRAILLE_RGBA: &[u8] = include_bytes!("link_braille.rgba");
/// ~25% coverage (64/255), override, hand-picked after reviewing bake_icons.py's own auto-suggested preview -- 12/96 dots lit at this threshold.
/// DEGRADED: the two interlocking chain ovals collapse into a single horizontal dot-row at every threshold; the 'two links' meaning does not survive, though the row itself is not noise.
const LINK_BRAILLE_ALPHA_THRESHOLD: u8 = 64;
static LINK_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        LINK_BRAILLE_RGBA,
        LINK_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- CircleFilled (circle-filled) -----------------------------------

const CIRCLE_FILLED_RGBA: &[u8] = include_bytes!("circle_filled.rgba");
static CIRCLE_FILLED_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(CIRCLE_FILLED_RGBA));

const CIRCLE_FILLED_BRAILLE_RGBA: &[u8] = include_bytes!("circle_filled_braille.rgba");
/// ~6% coverage (15/255), auto-selected by bake_icons.py::choose_threshold -- 16/96 dots lit at this threshold.
const CIRCLE_FILLED_BRAILLE_ALPHA_THRESHOLD: u8 = 15;
static CIRCLE_FILLED_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        CIRCLE_FILLED_BRAILLE_RGBA,
        CIRCLE_FILLED_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- CircleSlash (circle-slash) -------------------------------------

const CIRCLE_SLASH_RGBA: &[u8] = include_bytes!("circle_slash.rgba");
static CIRCLE_SLASH_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(CIRCLE_SLASH_RGBA));

const CIRCLE_SLASH_BRAILLE_RGBA: &[u8] = include_bytes!("circle_slash_braille.rgba");
/// ~40% coverage (102/255), auto-selected by bake_icons.py::choose_threshold -- 22/96 dots lit at this threshold.
const CIRCLE_SLASH_BRAILLE_ALPHA_THRESHOLD: u8 = 102;
static CIRCLE_SLASH_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        CIRCLE_SLASH_BRAILLE_RGBA,
        CIRCLE_SLASH_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Warning (warning) ----------------------------------------------

const WARNING_RGBA: &[u8] = include_bytes!("warning.rgba");
static WARNING_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(WARNING_RGBA));

const WARNING_BRAILLE_RGBA: &[u8] = include_bytes!("warning_braille.rgba");
/// ~35% coverage (89/255), auto-selected by bake_icons.py::choose_threshold -- 18/96 dots lit at this threshold.
const WARNING_BRAILLE_ALPHA_THRESHOLD: u8 = 89;
static WARNING_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        WARNING_BRAILLE_RGBA,
        WARNING_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Error (error) --------------------------------------------------

const ERROR_RGBA: &[u8] = include_bytes!("error.rgba");
static ERROR_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(ERROR_RGBA));

const ERROR_BRAILLE_RGBA: &[u8] = include_bytes!("error_braille.rgba");
/// ~40% coverage (102/255), auto-selected by bake_icons.py::choose_threshold -- 20/96 dots lit at this threshold.
const ERROR_BRAILLE_ALPHA_THRESHOLD: u8 = 102;
static ERROR_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        ERROR_BRAILLE_RGBA,
        ERROR_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Info (info) ----------------------------------------------------

const INFO_RGBA: &[u8] = include_bytes!("info.rgba");
static INFO_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(INFO_RGBA));

const INFO_BRAILLE_RGBA: &[u8] = include_bytes!("info_braille.rgba");
/// ~35% coverage (89/255), auto-selected by bake_icons.py::choose_threshold -- 20/96 dots lit at this threshold.
const INFO_BRAILLE_ALPHA_THRESHOLD: u8 = 89;
static INFO_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        INFO_BRAILLE_RGBA,
        INFO_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- RunAll (run-all) -----------------------------------------------

const RUN_ALL_RGBA: &[u8] = include_bytes!("run_all.rgba");
static RUN_ALL_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(RUN_ALL_RGBA));

const RUN_ALL_BRAILLE_RGBA: &[u8] = include_bytes!("run_all_braille.rgba");
/// ~45% coverage (115/255), auto-selected by bake_icons.py::choose_threshold -- 19/96 dots lit at this threshold.
const RUN_ALL_BRAILLE_ALPHA_THRESHOLD: u8 = 115;
static RUN_ALL_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        RUN_ALL_BRAILLE_RGBA,
        RUN_ALL_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Play (play) ----------------------------------------------------

const PLAY_RGBA: &[u8] = include_bytes!("play.rgba");
static PLAY_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(PLAY_RGBA));

const PLAY_BRAILLE_RGBA: &[u8] = include_bytes!("play_braille.rgba");
/// ~25% coverage (64/255), auto-selected by bake_icons.py::choose_threshold -- 18/96 dots lit at this threshold.
const PLAY_BRAILLE_ALPHA_THRESHOLD: u8 = 64;
static PLAY_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        PLAY_BRAILLE_RGBA,
        PLAY_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Sync (sync) ----------------------------------------------------

const SYNC_RGBA: &[u8] = include_bytes!("sync.rgba");
static SYNC_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(SYNC_RGBA));

const SYNC_BRAILLE_RGBA: &[u8] = include_bytes!("sync_braille.rgba");
/// ~25% coverage (64/255), auto-selected by bake_icons.py::choose_threshold -- 18/96 dots lit at this threshold.
const SYNC_BRAILLE_ALPHA_THRESHOLD: u8 = 64;
static SYNC_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        SYNC_BRAILLE_RGBA,
        SYNC_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- GoToFile (go-to-file) ------------------------------------------

const GO_TO_FILE_RGBA: &[u8] = include_bytes!("go_to_file.rgba");
static GO_TO_FILE_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(GO_TO_FILE_RGBA));

const GO_TO_FILE_BRAILLE_RGBA: &[u8] = include_bytes!("go_to_file_braille.rgba");
/// ~45% coverage (115/255), auto-selected by bake_icons.py::choose_threshold -- 21/96 dots lit at this threshold.
const GO_TO_FILE_BRAILLE_ALPHA_THRESHOLD: u8 = 115;
static GO_TO_FILE_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        GO_TO_FILE_BRAILLE_RGBA,
        GO_TO_FILE_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Pulse (pulse) --------------------------------------------------

const PULSE_RGBA: &[u8] = include_bytes!("pulse.rgba");
static PULSE_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(PULSE_RGBA));

const PULSE_BRAILLE_RGBA: &[u8] = include_bytes!("pulse_braille.rgba");
/// ~10% coverage (26/255), auto-selected by bake_icons.py::choose_threshold -- 20/96 dots lit at this threshold.
/// DEGRADED: the heartbeat zig-zag's short segments partially merge; a general spike/wave shape survives, the fine zig-zag detail does not.
const PULSE_BRAILLE_ALPHA_THRESHOLD: u8 = 26;
static PULSE_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        PULSE_BRAILLE_RGBA,
        PULSE_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Checklist (checklist) ------------------------------------------

const CHECKLIST_RGBA: &[u8] = include_bytes!("checklist.rgba");
static CHECKLIST_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(CHECKLIST_RGBA));

const CHECKLIST_BRAILLE_RGBA: &[u8] = include_bytes!("checklist_braille.rgba");
/// ~25% coverage (64/255), override, hand-picked after reviewing bake_icons.py's own auto-suggested preview -- 21/96 dots lit at this threshold.
/// DEGRADED: the checkmarks-in-a-list fine strokes read as a boxed/ruled texture, not legible individual ticks.
const CHECKLIST_BRAILLE_ALPHA_THRESHOLD: u8 = 64;
static CHECKLIST_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        CHECKLIST_BRAILLE_RGBA,
        CHECKLIST_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Eye (eye) ------------------------------------------------------

const EYE_RGBA: &[u8] = include_bytes!("eye.rgba");
static EYE_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(EYE_RGBA));

const EYE_BRAILLE_RGBA: &[u8] = include_bytes!("eye_braille.rgba");
/// ~30% coverage (77/255), override, hand-picked after reviewing bake_icons.py's own auto-suggested preview -- 12/96 dots lit at this threshold.
const EYE_BRAILLE_ALPHA_THRESHOLD: u8 = 77;
static EYE_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        EYE_BRAILLE_RGBA,
        EYE_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Layout (layout) ------------------------------------------------

const LAYOUT_RGBA: &[u8] = include_bytes!("layout.rgba");
static LAYOUT_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(LAYOUT_RGBA));

const LAYOUT_BRAILLE_RGBA: &[u8] = include_bytes!("layout_braille.rgba");
/// ~45% coverage (115/255), auto-selected by bake_icons.py::choose_threshold -- 32/96 dots lit at this threshold.
/// DEGRADED: 3 separate rounded-rect panels within one 16x16 viewBox collapse into a repeating texture; reads as hatching, not a distinguishable 2-or-3-panel grid.
const LAYOUT_BRAILLE_ALPHA_THRESHOLD: u8 = 115;
static LAYOUT_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        LAYOUT_BRAILLE_RGBA,
        LAYOUT_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- SplitHorizontal (split-horizontal) -----------------------------

const SPLIT_HORIZONTAL_RGBA: &[u8] = include_bytes!("split_horizontal.rgba");
static SPLIT_HORIZONTAL_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(SPLIT_HORIZONTAL_RGBA));

const SPLIT_HORIZONTAL_BRAILLE_RGBA: &[u8] = include_bytes!("split_horizontal_braille.rgba");
/// ~25% coverage (64/255), override, hand-picked after reviewing bake_icons.py's own auto-suggested preview -- 36/96 dots lit at this threshold.
const SPLIT_HORIZONTAL_BRAILLE_ALPHA_THRESHOLD: u8 = 64;
static SPLIT_HORIZONTAL_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        SPLIT_HORIZONTAL_BRAILLE_RGBA,
        SPLIT_HORIZONTAL_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- SplitVertical (split-vertical) ---------------------------------

const SPLIT_VERTICAL_RGBA: &[u8] = include_bytes!("split_vertical.rgba");
static SPLIT_VERTICAL_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(SPLIT_VERTICAL_RGBA));

const SPLIT_VERTICAL_BRAILLE_RGBA: &[u8] = include_bytes!("split_vertical_braille.rgba");
/// ~25% coverage (64/255), override, hand-picked after reviewing bake_icons.py's own auto-suggested preview -- 36/96 dots lit at this threshold.
const SPLIT_VERTICAL_BRAILLE_ALPHA_THRESHOLD: u8 = 64;
static SPLIT_VERTICAL_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        SPLIT_VERTICAL_BRAILLE_RGBA,
        SPLIT_VERTICAL_BRAILLE_ALPHA_THRESHOLD,
    )
});

// ---- Preview (preview) ----------------------------------------------

const PREVIEW_RGBA: &[u8] = include_bytes!("preview.rgba");
static PREVIEW_SIXEL: LazyLock<String> = LazyLock::new(|| build_sixel(PREVIEW_RGBA));

const PREVIEW_BRAILLE_RGBA: &[u8] = include_bytes!("preview_braille.rgba");
/// ~50% coverage (128/255), auto-selected by bake_icons.py::choose_threshold -- 25/96 dots lit at this threshold.
const PREVIEW_BRAILLE_ALPHA_THRESHOLD: u8 = 128;
static PREVIEW_BRAILLE: LazyLock<PixelCanvas> = LazyLock::new(|| {
    rgba_to_canvas(
        CanvasMode::Braille,
        BRAILLE_ICON_CELLS_WIDE,
        BRAILLE_ICON_CELLS_TALL,
        PREVIEW_BRAILLE_RGBA,
        PREVIEW_BRAILLE_ALPHA_THRESHOLD,
    )
});

